document.writeln("<!--全部-->");
document.writeln("		<div class=\'all\'>");
document.writeln("			<!--中间的div开始-->");
document.writeln("			<div class=\'middle\'>");
document.writeln("");
document.writeln("				<div class=\'middle_close\' style=\'float: right;font-size: 25px; \'>X</div>");
document.writeln("				<!--左边的登录开始-->");
document.writeln("				<div class=\'reg-left\'>");
document.writeln("					<form method=\'post\' class=\'form-field\'>");
document.writeln("						<!--手机号或账号登录的开始-->");
document.writeln("						<div class=\'reg-left-type\'>");
document.writeln("							<button type=\'button\' class=\'note-login\' id=\'inote-login\'>手机验证码登录</button>");
document.writeln("							<button type=\'button\' id=\'inormal-login\'>账号密码登录</button>");
document.writeln("							<!--手机号或账号登录的结束-->");
document.writeln("						</div>");
document.writeln("						<!--手机号的开始-->");
document.writeln("						<div class=\'form-field-text\'>");
document.writeln("							<i class=\'i-input fa fa-user-circle\' aria-hidden=\'true\'></i>");
document.writeln("							<input type=\'text\' placeholder=\'手机号\' class=\'text\' id='uid'/>");
document.writeln("");
document.writeln("						</div>");
document.writeln("						<!--短信验证的开始-->");
document.writeln("						<div class=\'form-field-text note-show\'>");
document.writeln("");
document.writeln("							<i class=\'i-input fa fa-lock fa-lg\'></i>");
document.writeln("							<input type=\'text\' placeholder=\'动态码\' class=\'text\' id='message' />");
document.writeln("							<input type=\'button\' value=\'获取手机动态码\' class=\'button--mini\'  id='getMessage' />");
document.writeln("							<input type=\'checkbox\' checked=\'checked\' /><span class=\'reg-left-span1\'> 自动登录</span>");
document.writeln("							<p class=\'reg-left-p1\'>未注册的手机号将自动创建为妙妙屋短租帐户</p>");
document.writeln("							<input type=\'button\' value=\'登录\' class=\'button\' id='messageLogin' />");
document.writeln("							<!--短信验证的结束-->");
document.writeln("						</div>");
document.writeln("						<!--账号登录的开始-->");
document.writeln("						<div hidden=\'hidden\' class=\'form-field-text inormal-show\'>");
document.writeln("");
document.writeln("							<i class=\'i-input fa fa-lock fa-lg\'></i>");
document.writeln("							<input type=\'password\' placeholder=\'密码\' class=\'upassword text\' id='pwd'/>");
document.writeln("						<p>");
document.writeln("							<span>验证码：</span>");
document.writeln("							<button type='button' class='layui-btn layui-btn-primary' data-appid='2011065062' id='TencentCaptcha' data-cbfn='callback'>滑动验证</button>");
document.writeln("						</p>");

document.writeln("							<input type=\'checkbox\' checked=\'checked\' /><span class=\'reg-left-span1\'> 自动登录</span>");
document.writeln("							<span id='logging_status'></span>");
document.writeln("							<input type=\'button\' value=\'登录\' class=\'button\' id='register02'/>");
document.writeln("							<p><span class=\'reg-left-span2\'>没有账号密码请</span> <span class=\'reg-left-span3\'>使用手机验证码登录</span></p>");
document.writeln("							<!--账号登录的结束-->");
document.writeln("						</div>");
document.writeln("");
document.writeln("					</form>");
document.writeln("					<!--左边的登录结束-->");
document.writeln("				</div>");
document.writeln("				<!--中间的div结束-->");
document.writeln("				<!--右边的其他登录开始-->");
document.writeln("				<div class=\'reg-right\'>");
document.writeln("					<p class=\'reg-right-p1\'>其他登录方式</p>");
document.writeln("					<!--微信登录-->");
document.writeln("					<p class=\'reg-right-p2 reg-right-p\'>");
document.writeln("						<a class=\'reg-right-span reg-right-span1\'>");
document.writeln("							<i class=\'i-span1 i-span fa fa-weixin\' aria-hidden=\'true\'></i>");
document.writeln("						</a>");
document.writeln("						<span class=\'reg-right-weixin reg-right-font\'>微信登录</span>");
document.writeln("					</p>");
document.writeln("					<!--qq登录-->");
document.writeln("					<p class=\'reg-right-p3 reg-right-p\'>");
document.writeln("						<a class=\'reg-right-span reg-right-span2\'>");
document.writeln("							<i class=\'i-span2 i-span fa fa-qq\' aria-hidden=\'true\'></i>");
document.writeln("						</a>");
document.writeln("						<span class=\'reg-right-qq reg-right-font\'>Q Q登录</span>");
document.writeln("					</p>");
document.writeln("					<!--微博登录-->");
document.writeln("					<p class=\'reg-right-p4 reg-right-p\'>");
document.writeln("						<a class=\'reg-right-span reg-right-span3\'>");
document.writeln("							<i class=\'i-span3 i-span fa fa-weibo\' aria-hidden=\'true\'></i>");
document.writeln("						</a>");
document.writeln("						<span class=\'reg-right-weibo reg-right-font\'>微博登录</span>");
document.writeln("					</p>");
document.writeln("					<!--右边的其他登录结束-->");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");